export const FETCH_COUTRIES_DATA = 'FETCH_COUTRIES_DATA';
export const FETCH_POPULATION_DATA = 'FETCH_POPULATION_DATA';
export const FETCH_DETAILS = 'FETCH_POPULATION_DATA';
export const FILTER_DATA = 'FILTER_DATA';
export const STOP_FILTER = 'STOP_FILTER';
export const RESET_DETAILS_STATE = 'RESET_DETAILS_STATE';
